### ISSUE TITLE
cant use commands in dev version of the mod

### ISSUE THREAD

**Issue by ArtiK045** [evilfactory/traitormod#16]
i used !help !points !addpoints !point !pointshop !role !write, there isnt any command that will work
how can i fix it?

**Comment by evilfactory** [comment]
Make sure you have lua installed.

**Comment by ArtiK045** [comment]
i have, maybe i have to use lua from github?

**Comment by ArtiK045** [comment]
![image](https://github.com/evilfactory/traitormod/assets/120784545/9258d8b7-7e5b-466b-aaa2-28baebbc808d)

**Comment by evilfactory** [comment]
Fixed the error, but the issue at hand seems to be caused by an invalid pointshop item, i suggest trying out the newest changes and looking at the new error.

**Comment by ArtiK045** [comment]
> Fixed the error, but the issue at hand seems to be caused by an invalid pointshop item, i suggest trying out the newest changes and looking at the new error.

ok gimme a second

**Comment by ArtiK045** [comment]
![image](https://github.com/evilfactory/traitormod/assets/120784545/fd27c631-cddd-408d-adee-17bb6b939264)

**Comment by evilfactory** [comment]
Fixed in 8c9682e

**Comment by ArtiK045** [comment]
btw i have randomly localized items in point shop
how can i localize all items?
i will help with it

**Comment by ArtiK045** [comment]
very nice, now there isnt any errors

**Comment by ArtiK045** [comment]
now dev version mod works well
