### ISSUE TITLE
pointshop broken again

### ISSUE THREAD

**Issue by ArtiK045** [evilfactory/traitormod#18]
![image](https://github.com/evilfactory/traitormod/assets/120784545/73680e8f-41de-4fe2-a2b8-d48bf97f655a)

**Comment by KARASIK123** [comment]
Да, здесь и вправду есть непереведённые наименования приборов требующих починки, но где спрятаны сами названия?

**Comment by evilfactory** [comment]
It seems your language file is missing a localization string? `PointshopWishCategory` more specifically

**Comment by ArtiK045** [comment]
maybe lemme check it

**Comment by ArtiK045** [comment]
ye, i updated translation, its ok
