### ISSUE TITLE
Can i install this mod on the normal lua? The workshop version.

### ISSUE THREAD

**Issue by DarkArtz0** [evilfactory/traitormod#7]
Is it possible and how can i do it? You didnt state a guide.

**Comment by evilfactory** [comment]
what

**Comment by DarkArtz0** [comment]
> what

I mean the workshop lua , on the steam workshop

**Comment by DarkArtz0** [comment]
> what

I mean the workshop lua , on the steam workshop

**Comment by evilfactory** [comment]
yes
